### ISSUE TITLE
Game Automatically Jumped to End Screen Before Completing Digging Minigame

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#100] opened 2021-03-08 03:00 UTC
### Description:
So unfortunately I haven't been able to produce this bug consistently but it has occured often enough that I thought it warranted an issue. Basically I start up the app and start playing the digging game and dig; however I stop before reaching the end and start pressing random keys (from memory it's been ctrl, shift, command, and enter, all entered randomly) and the game jump to the end. I can provide the files that were produced in the ouput folder if requested for review:
![image](https://user-images.githubusercontent.com/25377291/110269358-7e3f5f80-7f91-11eb-91d4-798342531fa9.png)

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open Battery.json
2. Set DigAmount to `10`
3. Save file
3. Start Client and Server
4. Dig normally until you reach the last block before the treasure
5. Press ctrl, shit, command, and enter over and over randomly

### Actual Result:

Game jumps to ending screen:
![image](https://user-images.githubusercontent.com/25377291/110269161-1d178c00-7f91-11eb-9802-105109d057ac.png)

### Expected Result:

Nothing should happen when pressing random keys that are not the digging key and game should proceed normally

**Comment by BryanChiu** [comment] 2021-03-12 22:04
Duplicate of https://github.com/BryanChiu/Mactivision/issues/77

**Closed** 2021-03-20 20:18 UTC
Labels: duplicate
