### ISSUE TITLE
Instructions for the feeding minigame should be clearer

### ISSUE THREAD

**Issue by Jailoodu** [BryanChiu/Mactivision#96] opened 2021-03-06 18:13 UTC
**Summary**: It is not clear whether the monster is only allowed to eat the food displayed, or if the food displayed is added to the previous set of acceptable foods.

**Visual proof**:
![image](https://user-images.githubusercontent.com/21979292/110216278-42ff3c80-7e7c-11eb-89c9-365db7360a59.png)

**Expected result**: In the instructions or the in-game monitor, it should state whether the monster can only eat the single food presented or a growing set of foods. 

**Actual result**: Instructions or the in-game monitor don't clearly state what the monster expects, leaving it up to the user to decide.

**Environment**: Microsoft Windows 10 Home, Google Chrome

**Severity**: Medium
**Priority**: Low

**Comment by BryanChiu** [comment] 2021-03-12 22:15
Duplicate of https://github.com/BryanChiu/Mactivision/issues/79

**Closed** 2021-03-28 04:14 UTC
Labels: duplicate
