### ISSUE TITLE
MaxGameTime Does not work when set to 0.01

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#90] opened 2021-03-04 16:01 UTC
Repro:
1. Edit Configuration File
2. Set MaxGameTime under FeederConfig to 0.0.1
3. Wait for food to drop on plate
4. Do not hit left or right on keyboard for 10 seconds

Observation:
MaxGameTime does not end at the correct time. The player can wait there before making a move for any amount of time surpassing 0.01 seconds set in config file.
Expectation:
MaxGameTime should have an effect or at least reset to default value

**Comment by DavidHospital** [comment] 2021-03-12 22:38
Duplicate of https://github.com/BryanChiu/Mactivision/issues/71

**Closed** 2021-03-20 23:15 UTC
Labels: duplicate
