### ISSUE TITLE
Layout of web page

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#115] opened 2021-03-08 10:50 UTC
## Description
When I click on the “Start Battery” button in the middle of main page, I find myself about to play a mini game. But it bothers me a lot that the frame of the game is not complete. And it takes me a while to find the full screen button on bottom right of the page. I think it would be better to place the full screen button in a conspicuous position.
## Environment
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/42874340/110311581-f4e66680-803e-11eb-9f0d-5f942c649ff4.png)
![image](https://user-images.githubusercontent.com/42874340/110311589-f879ed80-803e-11eb-88fb-fb90d3461921.png)
![image](https://user-images.githubusercontent.com/42874340/110311596-fadc4780-803e-11eb-9a76-2d10f351aafa.png)
## Expected Result
The full screen button should be placed in a more conspicuous position
## Severity
LOW

**Comment by BryanChiu** [comment] 2021-03-12 20:15
Duplicate of https://github.com/BryanChiu/Mactivision/issues/66

**Comment by teemh** [comment] 2021-03-22 20:29
Fixed with responsive template

**Closed by teemh** 2021-03-22 20:29 UTC
Labels: duplicate
