### ISSUE TITLE
Feeder "MaxGameTime" endstate does not trigger until L/R button pressed

### ISSUE THREAD

**Issue by anthonylou** [BryanChiu/Mactivision#112] opened 2021-03-08 09:52 UTC
In the "Feeder" level, ending the game via the `MaxGameTime` value does not trigger until the player sends a Left/Right key input. If the player does not submit any input, the level will indefinitely continue without automatically ending. 

**Steps to recreate:**
1. Start the client/server, and navigate to the "Feeder" level. 
2. Once the level has started, wait for the "MaxGameTime" time to elapse (default: 90.0s)
3. Verify that the level has not automatically ended. Press either the left or right key, and verify that the level clear screen appears. 

**Notes**: I have tested both left and right keys, and both cause the same behaviour. It seems that the input triggers an update that checks if `ElapsedTime >= MaxGameTime`.

**Comment by BryanChiu** [comment] 2021-03-12 20:44
Will change to game ending immediately. Will add line to Feeder and Digger output metric json to say if game ended because "MaxGameTime" reached

**Comment by BryanChiu** [comment] 2021-03-12 20:45
Duplicate of https://github.com/BryanChiu/Mactivision/issues/71

**Closed** 2021-03-20 21:38 UTC
Labels: duplicate
