### ISSUE TITLE
Screen is not fully accessible as the window shrinks 

### ISSUE THREAD

**Issue by robertjvardy** [BryanChiu/Mactivision#83] opened 2021-03-04 03:13 UTC
Steps to reproduce:
- run the app as instructed
- reduce the browser size by shrinking the window horizontally

Expected: full window should be accessible via scrolling horizontally
Actual: The left half of the screen is not accessible

Priority: high
severity: high 

![image](https://user-images.githubusercontent.com/47096316/109906003-b0894e00-7c6d-11eb-9b58-b8bca7fff112.png)

**Comment by Cmon16** [comment] 2021-03-12 21:56
Duplicate of #81

**Closed** 2021-03-21 00:59 UTC
Labels: duplicate
