### ISSUE TITLE
No lose even if you feed the monster all the foods available

### ISSUE THREAD

**Issue by mudarthc** [BryanChiu/Mactivision#60] opened 2021-02-25 19:31 UTC
**Bug** :  Even if you feed the monster all the foods available (always clicking the right arrow) you still win and continue to next level.
**Steps**:  
https://drive.google.com/file/d/1jaXt9gzS-5EkxX0hAy497W6fIEchINN2/view?usp=sharing
**Environment**: Macos
**Expected**: expected some sort of repercussion if you feed the monster the wrong food
**Actual**:  you can feed the monster anything, I think this has great visuals but defeats the purpose of a game if you win in all situations.

**Comment by DavidHospital** [comment] 2021-03-12 19:45
duplicate of https://github.com/BryanChiu/Mactivision/issues/57

**Comment by mudarthc** [comment] 2021-03-13 00:32
I dont believe this is a duplicate, #57 describes putting all the food in the trash while this issue is describes giving all the food to the monster.

**Comment by DavidHospital** [comment] 2021-03-16 17:54
You're right, this isn't a duplicate. However, it is an invalid issue as there are no "win" or "lose" condition in these minigames. The player should play each minigame in the order decided by the researcher, and therefore, the sequence of games is not determined by the user's score in each game; they will move onto the next minigame in the battery regardless if they "win" or "lose". I will mark this as `documentation`, as we believe our documentation isn't clear enough to explain this.

**Comment by BryanChiu** [comment] 2021-03-20 18:25
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated

**Closed by BryanChiu** 2021-03-20 18:25 UTC
Labels: documentation
