### ISSUE TITLE
Keyboard Setting

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#121] opened 2021-03-08 11:44 UTC
## Description:
I am trying to replace “DigKey” value from “B” to “1” to test the gaming engine. Disappointingly, “1” on the keyboard won’t work at all.

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	set DigKey to “1” in Battery.json
2.	restart the first mini game
3.	press “1” on keyboard and nothing happens
 ![image](https://user-images.githubusercontent.com/42874340/110317121-a341da00-8046-11eb-9b58-7d0e7ab40a17.png)

## Expected Result:
“1” on the keyboard should work as good as “B”

## Severity: 
LOW

**Comment by BryanChiu** [comment] 2021-03-12 19:52
Documentation links to valid [Unity KeyCodes](https://docs.unity3d.com/ScriptReference/KeyCode.html). In this case, "Alpha1" should have been used.

**Comment by BryanChiu** [comment] 2021-03-12 21:00
Duplicate of https://github.com/BryanChiu/Mactivision/issues/73

**Closed** 2021-03-20 18:29 UTC
Labels: invalid, wontfix
