### ISSUE TITLE
Sidebar function in spotlight level?

### ISSUE THREAD

**Issue by mudarthc** [BryanChiu/Mactivision#65] opened 2021-02-25 20:31 UTC
**Bug** : Not too sure what the sidebar is an indicator of. It has two red areas and a white area in the middle and is only affected by the firework button. 

**Steps**: 1. navigate to spotlight level 2. click "L" repeatedly 3. notice changes in sidebar

**Environment**: macos

**Expected**:  a clearer indication of what the sidebar is supposed to portray 

**Actual**: Regardless. of what level the sidebar is at there is no change in outcome 

![Screen Shot 2021-02-25 at 3 16 37 PM](https://user-images.githubusercontent.com/35268733/109213304-6dffd700-777e-11eb-8b17-85a5916d19ac.png)

**Comment by DavidHospital** [comment] 2021-03-12 19:52
Duplicate of https://github.com/BryanChiu/Mactivision/issues/62

**Comment by mudarthc** [comment] 2021-03-13 00:45
I dont believe this is a duplicate, in #62 i was talking about a different behaviour (ie not pressing any keys and still winning, while this issue is in relation the sidebar not having a clear purpose)

**Comment by DavidHospital** [comment] 2021-03-16 17:57
I see. This is a documentation issue then

**Comment by BryanChiu** [comment] 2021-03-20 18:24
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated

**Closed by BryanChiu** 2021-03-20 18:24 UTC
Labels: documentation
