### ISSUE TITLE
Monster has Inconsistent Reactions to Bad Foods

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#82] opened 2021-03-04 03:13 UTC
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start the application client and server
2. Navigate to the game page with a smaller device screen
3. Play the 2nd game (Feeder)

### Expected:
The monster acts the same for all bad foods

### Actual:
Some foods the monster moves to the end of the pit and spits it out, sometimes it stays still and does nothing. Specifically with the green hamburger

**Comment by DavidHospital** [comment] 2021-03-12 22:15
We are unable to reproduce this issue, we think it could easily be caused by the player's error (forgetting which foods are accepted), however if you have any other information such as the seed used as well as the input and output files used in the game instance that produced this bug, we can further investigate.

**Comment by DavidHospital** [comment] 2021-03-30 16:24
Reporter never got back to us so we will close this issue.

**Closed by DavidHospital** 2021-03-30 16:24 UTC
Labels: question
